//
//  ExpirableUuid.swift
//  GithubBusApp
//
//  Created by James Mallison on 25/02/2018.
//  Copyright © 2018 J7mbo. All rights reserved.
//

import Foundation
import CoreData

/// Represents a uuid with an expiry date
class ExpirableUuid: NSObject, UnmanagedEntity
{
    /// The number of days until a uuid is considered expired
    private let expiresInDays: Int = 2

    /// Used for identifying an `NSManagedObject`, for deletion and updating purposes for example
    @objc public var id: UnmanagedEntityId?
    
    /// The unique id
    @objc public let uuid: String

    /// The creation date
    @objc public let created: Date

    /// Whether or not the current date is past the date of expiration
    public var hasExpired: Bool {
        get {
            return Date() > Calendar.current.date(byAdding: .day, value: expiresInDays, to: self.created)!
        }
    }
    
    /// Initialise a `ExpirableUuid`
    ///
    /// - Parameters:
    ///   - uuid:    The uuid, typically generated by `UuidGenerator`
    ///   - created: The date the uuid was created
    ///   - id:      The `NSManagedObjectID`, archiveable as a url string, if already persisted in core data
    init(uuid: String, created: Date, id: UnmanagedEntityId? = nil) {
        self.uuid    = uuid
        self.created = created
        self.id      = id
    }
}
